MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = 3309
MYSQL_USERNAME = "zduan"
MYSQL_PASSWORD = "11111111"
MYSQL_UNIX_SOCKET = "/var/run/mysqld/mysqld.sock"
MYSQL_DBNAME = "foodrecom"

CRAWLING_SERVER_HOST = "localhost"
CRAWLING_SERVER_PORT = 4040
SLEEP_CRAWLING_IN_SECONDS = 2


MONGO_DB_HOST = "localhost"
MONGO_DB_PORT = 27017

YELP_DB_NAME = "yelp-info"
YELP_TABLE_NAME = "yelp"

YELP_INFO_TASK_QUEUE_URL = "amqp://tgfywhzj:rGu2ImqiXK0PnjlgaiUcwJc0Arq5vo9-@donkey.rmq.cloudamqp.com/tgfywhzj"
YELP_INFO_TASK_QUEUE_NAME = "yelp-info-recording-task-queue"
SLEEP_SCRAPING_IN_SECONDS = 1

RESTUARANT_INFO_SERVER_HOST = "localhost"
RESTUARANT_INFO_SERVER_PORT = 5000

GEO_SERVER_HOST = "localhost"
GEO_SERVER_PORT = 4000

USER_SERVER_HOST = "localhost"
USER_SERVER_PORT = 7000

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

USER_TABLE_NAME = "user"
USER_DB_NAME = "ee-user"